services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: mydatabase

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: 274197531864.dkr.ecr.eu-north-1.amazonaws.com/task-manager-api:${IMAGE_TAG}
    container_name: task_manager_api
    environment:
      DATABASE_URL: postgresql://myuser:mysecurepassword@postgres:5432/mydatabase
    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
