apiVersion: apps/v1
kind: Deployment

metadata:
  name: task-manager-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: task-manager-api

  template:
    metadata:
      labels:
        app: task-manager-api

    spec:
      containers:
        - name: api
          image: task-manager-api:latest
          imagePullPolicy: Never

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL

          ports:
            - containerPort: 8000
